# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.

# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
  include:
  - master
 paths:
   exclude:
     - release-pipeline.yaml
  
  
pool: 
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  MyRunNumber: '1.0.0-CI-$(Build.BuildNumber)'
  MyDate: '1.0.0-CI-$(Date:yyyyMMdd)$(Rev:.r)-$(tag)'
  Version: '$(Major).$(Minor).$(Patch)-$(tag)'
  Maj: '1'
  Min: '2'
  Pat: $[counter(format('{0}.{1}', variables['Maj'], variables['Min']), 0)]
  Version2: '$(Maj).$(Min).$(Pat)-$(tag)'
  query: 'SELECT {0} FROM {0}-{0}-{0}-{0}'
  TestFormat: $[format(variables['query'], 'Column','Table', 'Condition')]

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(Maj).$(Min).$(Pat)-$(tag)

steps:
- bash: |
    echo "##vso[task.setvariable variable=sauce]crushed tomatoes"

# Use the variable
# "$(sauce)" is replaced by the contents of the `sauce` variable by Azure Pipelines
# before handing the body of the script to the shell.
- bash: |
    echo my pipeline variable is $(sauce)
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: | 
       echo $MYVAR
  env:
    MyVar: $(sauce)
- task: Bash@3
  name: 'asa_query_into_variable1'
  displayName: 'Export ASA query text into pipeline variable 1'
  inputs:
    targetType: 'inline'
    script: |
      set -euxo pipefail
      export COLUMN='COLUMNA'
      export TABLE='TABLA'
      export CONDITION='CONDITION'
      MYVAR=''
      ls
      envsubst < cat ./query.txt | awk '{printf "%s\\\\n", $0}' > '$MYVAR'
      echo $MYVAR
      echo "##vso[task.setvariable variable=query]\"`cat < ./query.txt | awk '{printf "%s\\\\n", $0}'`\""
    workingDirectory: '$(Build.SourcesDirectory)'
- bash: |
    echo $(query)
- task: Bash@3
  name: 'asa_query_into_variable'
  displayName: 'Export ASA query text into pipeline variable 2'
  inputs:
    targetType: 'inline'
    script: |
      set -euxo pipefail
      export COLUMN='COLUMNA'
      export TABLE='TABLA'
      export CONDITION='CONDITION'
      ls
      echo "##vso[task.setvariable variable=query]\"`envsubst < ./query.txt | awk '{printf "%s\\\\n", $0}'`\""
    workingDirectory: '$(Build.SourcesDirectory)'
- bash: |
    echo $(query)

- bash: |
    COLUMN='COLUMNA'
    TABLE='TABLA'
    CONDITION='CONDITION'
    echo $(query)
    echo "##vso[task.setvariable variable=TestFormat]$(query)"
- bash: |
    echo $(TestFormat)
- bash: | 
    API_URL="$SYSTEM_TEAMFOUNDATIONCOLLECTIONURI$SYSTEM_TEAMPROJECTID/_apis/git/repositories/$BUILD_REPOSITORY_ID/commits/$BUILD_SOURCEVERSION/changes?api-version=5.1" 
    echo $API_URL

- bash: | 
    API_URL="$SYSTEM_TEAMFOUNDATIONCOLLECTIONURI$SYSTEM_TEAMPROJECTID/_apis/git/repositories/$(Build.Repository.ID)/commits/$(Build.Repository.ID)/changes?api-version=5.1" 
    echo $API_URL
    curl GET -H "Content-Type: application/json" "$API_URL"
- script: dotnet build --configuration $(buildConfiguration) /p:Version=$(Version)
  displayName: 'dotnet build $(buildConfiguration) /p:Version=$(Version)'



- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'prd'



