# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.

# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
  include:
  - master
 paths:
   exclude:
     - release-pipeline.yaml
  
  
pool: 
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  MyRunNumber: '1.0.0-CI-$(Build.BuildNumber)'
  MyDate: '1.0.0-CI-$(Date:yyyyMMdd)$(Rev:.r)-$(tag)'
  Version: '$(Major).$(Minor).$(Patch)-$(tag)'
  Maj: '1'
  Min: '2'
  Pat: $[counter(format('{0}.{1}', variables['Maj'], variables['Min']), 0)]
  Version2: '$(Maj).$(Min).$(Pat)-$(tag)'

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(Maj).$(Min).$(Pat)-$(tag)

steps:
- script: echo $(MyRunNumber) # display MyRunNumber
- script: echo $(Build.BuildNumber) #display Run Number
- script: echo $(MyDate) #display My Date
- script: echo $(Version) #display My Version
- script: echo $(Version2) #display My Version2
- script: echo $(Build.SourceVersion) Commit ID
- script: echo $(Build.Repository.ID) Repository Id

- script: dotnet build --configuration $(buildConfiguration) /p:Version=$(Version)
  displayName: 'dotnet build $(buildConfiguration) /p:Version=$(Version)'



- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'prd'

- bash: | 
    API_URL="${SYSTEM_TEAMFOUNDATIONCOLLECTIONURI}${SYSTEM_TEAMPROJECTID}/_apis/git/repositories/${Build.Repository.ID}/commits/${Build.SourceVersion}/changes?api-version=5.1" 
    echo $API_URL

