# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.

# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
  include:
  - master
  
  
pool: 
  vmImage: 'vs2017-win2016'

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(Major).$(Minor).$(Patch)-$(tag)

variables:
  buildConfiguration: 'Release'
  MyRunNumber: '1.0.0-CI-$(Build.BuildNumber)'
  MyDate: '1.0.0-CI-$(Date:yyyyMMdd)$(Rev:.r)-$(tag)'
  Version: '$(Major).$(Minor).$(Patch)-$(tag)'

steps:
- script: echo $(MyRunNumber) # display MyRunNumber
- script: echo $(Build.BuildNumber) #display Run Number
- script: echo $(MyDate) #display My Date
- script: echo $(Version) #display My Version

- script: dotnet build --configuration $(buildConfiguration) /p:Version=$(Version)
  displayName: 'dotnet build $(buildConfiguration) /p:Version=$(Version)'

- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'prd'
