# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: echo $(Build.SourceVersion) Commit ID

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DownloadBuildArtifacts@0
  displayName: 'Download Package artifacts'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProject)'
    pipeline: 'JonatanMedinilla.pipelines-dotnet-core'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latestFromBranch'
    branchName: '$(Build.SourceBranch)'
    downloadType: 'single'
    artifactName: 'prd'
    downloadPath: '$(System.ArtifactsDirectory)'

- script: echo $(Release.Artifacts.prd.SourceVersion) Commit ID Artifact